### ISSUE TITLE
date is not printing 

### ISSUE THREAD

**Issue by vamshi-12527** [BlockySite/community#11]
### What happened?

![Screenshot 2022-01-18 171209](https://user-images.githubusercontent.com/80966047/149931196-09c03790-a941-456f-806f-845fe7b7d62b.png)
![Screenshot 2022-01-18 171739](https://user-images.githubusercontent.com/80966047/149932140-ec296274-d520-44c9-a42b-636845fcd48d.png)

I am getting a problem with the creator which is not able to print the given date 

### Relevant log output

```shell
![Screenshot 2022-01-18 171209](https://user-images.githubusercontent.com/80966047/149931196-09c03790-a941-456f-806f-845fe7b7d62b.png)
![Screenshot 2022-01-18 171739](https://user-images.githubusercontent.com/80966047/149932140-ec296274-d520-44c9-a42b-636845fcd48d.png)
```

**Comment by shiva-sandupatla** [comment]
@vamshi-12527 , Working on it

**Comment by shiva-sandupatla** [comment]
We have implemented your feature, please check and close the issue

**Comment by vamshi-12527** [comment]
Ok, its working
