### ISSUE TITLE
IMAGE NOT DISPLAYED IN PREVIEW 

### ISSUE THREAD

**Issue by dns144** [BlockySite/community#5]
### What happened?

![Screenshot (21)](https://user-images.githubusercontent.com/95041758/143689317-370b925c-140e-4627-b99f-66a02d273941.png)

<img width="560" alt="blocks" src="https://user-images.githubusercontent.com/95041758/143689325-83d335bd-2290-4179-b170-f83271b748d8.png">

![Screenshot (20)](https://user-images.githubusercontent.com/95041758/143689315-aac45c52-30eb-497f-9270-4f1d2f569a5a.png)

HELLO 
ACCORODING TO ABOVE IMAGES I HAVE CREATED MY WEBSITE,
 AT TIME OF PREVIEW I HAVE FOUND A BUG 
THE SELECETED IMAGE NOT DISPLAYED WHEN I CLICK ON BUTTON

### What browser do you use?

Chrome

**Comment by suryadevelope** [comment]
i checked it its working

**Comment by shiva-sandupatla** [comment]
@suryadevelope  when the above logic is implemented and saved project and reloaded then clicked on preview and clicked on button, now the image is not displaying. please have a look.

![image](https://user-images.githubusercontent.com/47274553/143766113-a5752916-fa0e-433a-991a-9c5defa9ef3e.png)
