### ISSUE TITLE
PARAGARH ISSUE

### ISSUE THREAD

**Issue by dns144** [BlockySite/community#6]
### What happened?

![image](https://user-images.githubusercontent.com/95041758/146972638-7dac079a-6aac-427f-b977-4a9aec666473.png)
Hello @blockysite-official 
Enlarge the textbox in paragraph
and Add multiline paragraph system in it.

**Comment by shiva-sandupatla** [comment]
@dns144, I am working on it!

**Comment by shiva-sandupatla** [comment]
@dns144, It is fixed. please verify. Also @suryadevelope please have a look at this issue. Update me so that I can close issue.
