### ISSUE TITLE
when started to write something in creator then I got bug/warnings please fix and 

### ISSUE THREAD

**Issue by vamshi-12527** [BlockySite/community#9]
### What happened?

![image](https://user-images.githubusercontent.com/80966047/147492972-4e30c770-986c-4b78-941a-e04d76c7e277.png)

**Comment by shiva-sandupatla** [comment]
Hey, @vamshi-12527

Can you please comment below on what made you close the issue?

**Comment by vamshi-12527** [comment]
Its wrong issue
